### ISSUE TITLE
Audio Quality

### ISSUE THREAD

**Issue by polyphantmgs** [LUSHDigital/lrpi_record#14]
Simon Emmerson - head of Music at Lush says audio quality is very low.

**Comment by polyphantmgs** [comment]
high frequencies are lost - comparison to MP3.
Distorting at certain points.
Look at export?
Decrease volume output of Pi?

**Comment by pisuke** [comment]
@polyphantmgs thanks for feedback. At the moment the audio is processed by the Onkyo using DTS.
@paulharter has been working on getting the 5.1 direct output, which we've proved works when you were in the lab on Monday, so Simon should check it again once we update the code. Has Simon assessed this in Poole or Liverpool?
Ideally, we'd prepare for this meeting and test two different audio players on the Pi, file quality and volume settings and then lock them, but all after having enabled pure 5.1 audio hdmi output.
