### ISSUE TITLE
ADDITION - export XML from Vezer and send to file

### ISSUE THREAD

**Issue by polyphantmgs** [LUSHDigital/lrpi_record#7]
To speed up publishing process.

**Comment by pisuke** [comment]
Linked to https://github.com/LUSHDigital/lrpi_record/issues/12

**Comment by pisuke** [comment]
Now working. Added the [lrpi_xml2srt.py](https://github.com/LUSHDigital/lrpi_record/blob/master/lrpi_xml2srt.py) new converter program.
