### ISSUE TITLE
5.1 audio - only playing in stereo 

### ISSUE THREAD

**Issue by polyphantmgs** [LUSHDigital/lrpi_record#8]
Only stereo, no 5.1 audio output

**Comment by bungeejim** [comment]
To be even with no file being played the amp is only seeing a stereo output from the communication down the HDMI cable. When I plug my laptop in it switches to 5.1. We played the test file mp4 on my laptop and it came out stereo. So it maybe the file format as well and the Pi

**Comment by paulharter** [comment]
can export as m4a with 6 channels of high quality aac with ffmpeg - need to test through 5.1 amp in arup

**Comment by paulharter** [comment]
Have made a change to display code to avoid any interference with alsa audio mixer and added --layout=5.1 to omxplayer commands. This seems to reliably play out 5.1 with both models of Onkyo in direct mode.

Still needs on site tests so will now push to production
